// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLQfPIhELH625ascllxfnYIoJYTL1q6zA',
    appId: '1:132095266991:web:913be3c0b224671fee845a',
    messagingSenderId: '132095266991',
    projectId: 'blood-donation-39ebd',
    authDomain: 'blood-donation-39ebd.firebaseapp.com',
    databaseURL: 'https://blood-donation-39ebd-default-rtdb.firebaseio.com',
    storageBucket: 'blood-donation-39ebd.appspot.com',
    measurementId: 'G-PG2NB3VPYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABhEcMxZX5JDUdmbm_ezHqb8Md1ywCJCk',
    appId: '1:132095266991:android:2d94162d7045ae51ee845a',
    messagingSenderId: '132095266991',
    projectId: 'blood-donation-39ebd',
    databaseURL: 'https://blood-donation-39ebd-default-rtdb.firebaseio.com',
    storageBucket: 'blood-donation-39ebd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ZEf7SDua2ZOSc6uWrqh-hE7_pAG7OlA',
    appId: '1:132095266991:ios:23cc194b47bcbc18ee845a',
    messagingSenderId: '132095266991',
    projectId: 'blood-donation-39ebd',
    databaseURL: 'https://blood-donation-39ebd-default-rtdb.firebaseio.com',
    storageBucket: 'blood-donation-39ebd.appspot.com',
    androidClientId: '132095266991-0ne0p4oj4jbfdqceev6i1emon7mhl3jh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ZEf7SDua2ZOSc6uWrqh-hE7_pAG7OlA',
    appId: '1:132095266991:ios:23cc194b47bcbc18ee845a',
    messagingSenderId: '132095266991',
    projectId: 'blood-donation-39ebd',
    databaseURL: 'https://blood-donation-39ebd-default-rtdb.firebaseio.com',
    storageBucket: 'blood-donation-39ebd.appspot.com',
    androidClientId: '132095266991-0ne0p4oj4jbfdqceev6i1emon7mhl3jh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLQfPIhELH625ascllxfnYIoJYTL1q6zA',
    appId: '1:132095266991:web:14f955c26697b0f1ee845a',
    messagingSenderId: '132095266991',
    projectId: 'blood-donation-39ebd',
    authDomain: 'blood-donation-39ebd.firebaseapp.com',
    databaseURL: 'https://blood-donation-39ebd-default-rtdb.firebaseio.com',
    storageBucket: 'blood-donation-39ebd.appspot.com',
    measurementId: 'G-CHLNSQBLNF',
  );
}
